@startuml
actor Gebruiker

participant AuthController
participant AuthControllerExceptionHandler
participant AuthService
participant WireMockAdapter
participant WireMockDriver

Gebruiker -> AuthController: GET /login\n{username, password}\n-> userAuthorization
AuthController -> AuthService: authorizeUser(userAuthorization)
AuthService -> WireMockAdapter: getRole(userAuthorization)
WireMockAdapter -> WireMockDriver: loginResponse = login(userAuthorization)
WireMockAdapter <- WireMockDriver: JSON
WireMockAdapter -> WireMockAdapter: token = parse JSON
WireMockAdapter -> WireMockDriver: checkAppAccessResponse = checkAppAccess(userAuthorization, token)
WireMockAdapter <- WireMockDriver: JSON
WireMockAdapter -> WireMockAdapter: userAccessInfo = parse JSON
AuthService <- WireMockAdapter: userAccessInfo
AuthController <- AuthService: userAccessInfo
Gebruiker <- AuthController: userAccessInfo

@enduml
