@startuml

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

left to right direction

SHOW_PERSON_OUTLINE()

AddRelTag("sync/async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())

title Dynamic diagram voor het Triptop systeem met gebruik van meerdere hotel apis

Person(reiziger, Reiziger, "Een persoon die een reis samen wilt stellen")

Container(frontend, "Frontend", $techn="JS/React", $descr="Laat de pagina zien aan de gebruiker.", $tags="", $link="")
System_Ext(wiremock, "Identity Provider", "Geeft een token terug als je een geldige gebruikersnaam en wachtwoord geeft. WireMock")
System_Ext(overnachting1, "Overnachting service", "Booking.com api service")
System_Ext(overnachting2, "Overnachting service", "TripAdvisor api service")

Container_Boundary("Container", "Backend", $tags="") {
    Component(authController, "Autorisatie Controller", $techn="Java/Spring Boot Controller", $descr="Inloggen, account informatie, etc", $tags="", $link="")
    Component(reisController, "Reis Controller", $techn="Java/Spring Boot Controller", $descr="Voegt bouwstenen toe aan een reis, en kan de volledige reis ophalen", $tags="", $link="")
    Component(authService, "Autorisatie Service", $techn="Java/Spring Boot Service", $descr="Connectie met OAuth provider, account data ophalen vanuit klant database", $tags="", $link="")
    Component(reisService, "Reis Service", $techn="Java/Spring Boot Service", $descr="Bouwstenen toevoegen aan een reis, ophalen volledige reis", $tags="", $link="")
    }



reiziger --> frontend : 1. Gaat naar de login pagina
frontend --> authController : 2. Logt in via
authController --> authService : 3. Gebruikt
authService --> wiremock : 4. Autoriseert gebruikers via
wiremock --> authService : 5. Geeft token / gegevens terug
authService --> authController : 6. Geeft token terug
authController --> frontend : 7. wordt ingelogd
frontend --> reisController : 8. Voegt bouwstenen aan reis toe
reisController --> reisService : 9. Gebruikt
reisService --> overnachting1 : 10. Vraagt mogelijke overnachtingen op
reisService --> overnachting2 : 10. Vraagt mogelijke overnachtingen op
overnachting1 --> reisService : 11. Geeft mogelijke overnachtingen terug
overnachting2 --> reisService : 11. Geeft mogelijke overnachtingen terug
reisService --> reisController : 12. Geeft mogelijke overnachtingen terug
reisController --> frontend : 13. Laat mogelijke overnachtingen zien


SHOW_LEGEND()

@enduml