@startuml

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

left to right direction
SHOW_PERSON_OUTLINE()

AddRelTag("sync/async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())

title Component diagram voor de backend container voor de "Fault Tolerance" ontwerpvraag

Container(frontend, "Frontend", $techn="JS/React", $descr="Laat de pagina zien aan de gebruiker.", $tags="", $link="")

System_Ext(wiremock, "Identity Provider", "Geeft een token terug als je een geldige gebruikersnaam en wachtwoord geeft. WireMock")

Container_Boundary("key_boundary", "Backend container", $tags="") {
    ' CONTROLLERS
    Component(authController, "Autorisatie Controller", $techn="Java/Spring Boot Controller", $descr="Inloggen, account informatie, etc", $tags="", $link="")

    ' CONTROLLER relations
    Rel(frontend, authController, "Logt in via", $techn="HTTP(S)/JSON", $tags="", $link="")

    ' SERVICES
    Component(authService, "Autorisatie Service", $techn="Java/Spring Boot Service", $descr="Connectie met OAuth provider, account data ophalen vanuit klant database", $tags="", $link="")

    ' SERVICE relations
    Rel(authController, authService, "Gebruikt", $tags="", $link="")

    ' EXTERN
    Rel(authService, wiremock, "Autoriseert gebruikers via", $techn="HTTP(S)/JSON", $tags="", $link="")
}

@enduml