@startuml

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

left to right direction
SHOW_PERSON_OUTLINE()

AddRelTag("sync/async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())

title Component diagram voor de backend container van het Triptop systeem

Container(frontend, "Frontend", $techn="JS/React", $descr="Laat de pagina zien aan de gebruiker.", $tags="", $link="")

System_Ext(wiremock, "Identity Provider", "Geeft een token terug als je een geldige gebruikersnaam en wachtwoord geeft. WireMock")

System_Ext(overnachting1, "Overnachting service", "Booking.com api service")
System_Ext(overnachting2, "Overnachting service", "TripAdvisor api service")


Container_Boundary("key_boundary", "Backend container", $tags="") {
    ' CONTROLLERS
    Component(authController, "Autorisatie Controller", $techn="Java/Spring Boot Controller", $descr="Inloggen, account informatie, etc", $tags="", $link="")
    Component(reisController, "Reis Controller", $techn="Java/Spring Boot Controller", $descr="Voegt bouwstenen toe aan een reis, en kan de volledige reis ophalen", $tags="", $link="")
    Component(bestellingController, "Bestelling Controller", $techn="Java/Spring Boot Controller", $descr="Overzicht van een bestelling ophalen en betalen", $tags="", $link="")

    ' CONTROLLER relations
    Rel(frontend, authController, "Logt in via", $techn="HTTP(S)/JSON", $tags="", $link="")
    Rel(frontend, reisController, "Voegt bouwstenen aan reis toe", $techn="HTTP(S)/JSON", $tags="", $link="")
    Rel(frontend, bestellingController, "Bekijkt bestelling en betaalt via", $techn="HTTP(S)/JSON", $tags="", $link="")

    ' SERVICES
    Component(authService, "Autorisatie Service", $techn="Java/Spring Boot Service", $descr="Connectie met OAuth provider, account data ophalen vanuit klant database", $tags="", $link="")
    Component(reisService, "Reis Service", $techn="Java/Spring Boot Service", $descr="Bouwstenen toevoegen aan een reis, ophalen volledige reis", $tags="", $link="")

    ' SERVICE relations
    Rel(authController, authService, "Gebruikt", $tags="", $link="")
'    Rel(authService, klantService, "Gebruikt", $tags="", $link="")
    Rel(reisController, reisService, "Gebruikt", $tags="", $link="")
    Rel(bestellingController, reisService, "Gebruikt", $tags="", $link="")

    ' EXTERN
    Rel(authService, wiremock, "Autoriseert gebruikers via", $techn="HTTP(S)/JSON", $tags="", $link="")
    Rel(reisService, overnachting1, "Boekt een gekozen overnachting via", $techn="HTTP(S)/JSON", $tags="", $link="")
    Rel(reisService, overnachting2, "Boekt een gekozen overnachting via", $techn="HTTP(S)/JSON", $tags="", $link="")

}

SHOW_LEGEND()

@enduml