@startuml

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

SHOW_PERSON_OUTLINE()

AddRelTag("sync/async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())

title Container diagram voor het triptop systeem

Person(reiziger, Reiziger, "Een persoon die een reis samen wilt stellen")
Person(reisagent, Reisagent, "Helpt reiziger bij het samenstellen van een reis")

System_Ext(wiremock, "Identity Provider", "Geeft een token terug als je een geldige gebruikersnaam en wachtwoord geeft. WireMock")
System_Ext(routeplanner, "Routeplanner Service: Google Maps", "Geeft een map terug als je een locatie geeft")
System_Ext(opentable, "Opentable API", "API voor reserveren van restaurants")
System_Ext(overnachting, "Overnachting service", "Booking.com api service")
System_Ext(uber, "Uber service", "Uber API")

System_Boundary("key_boundary", "Triptop", $tags="") {
    Container(frontend, "Frontend", $techn="JS/React", $descr="Laat de pagina zien aan de gebruiker.", $tags="", $link="")
    Container(backend, "Backend", $techn="Java/Spring Boot", $descr="Laat locaties op die gekozen worden op de route door de gebruiker.", $tags="", $link="")
    ContainerDb(db, "Database", $techn="SQL/MySQL", $descr="Slaat informatie op vanuit de backend.", $tags="", $link="")
    Rel(reiziger, frontend, "Plant een vakantietrip met", $techn="HTML/HTTP(S)", $tags="", $link="")
    Rel(reisagent, frontend, "Helpt reiziger bij het samenstellen van een reis", $techn="HTML/HTTP(S)", $tags="", $link="")
    Rel(frontend, backend, "Slaat route van gebruiker op, dmv de REST API.", $techn="JSON/HTTP(S)", $tags="", $link="")
    Rel(backend, db, "Geeft en slaat informatie van de backend op.", $techn="TCP/IP/SQL", $tags="", $link="")
    Rel(backend, wiremock, "Controleert of de gebruikersnaam/wachtwoord input correct is", $techn="(?)", $tags="", $link="")
    Rel(backend, opentable, "Haalt restaurants op en maakt reserveringen", $techn="JSON/HTTP(S)", $tags="", $link="")
    Rel(backend, overnachting, "Zoekt overnachtingen via", $techn="JSON/HTTP(S)", $tags="", $link="")
    Rel(backend, uber, "Haalt vervoersinformatie op", $techn="JSON/HTTP(S)", $tags="", $link="")
    Rel(frontend, routeplanner, "Verkrijgt een map op basis van input van de gebruiker", $techn="(?)", $tags="", $link="")
 }

@enduml