@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' convert it with additional command line argument -DRELATIVE_INCLUDE="./.." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
  !include %get_variable_value("RELATIVE_INCLUDE")/C4_Container.puml
!else
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!endif

SHOW_PERSON_OUTLINE()

AddRelTag("sync/async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())

LAYOUT_WITH_LEGEND()

title Dynamic Component Diagram voor de API Application container van verouderde API's

Container(webapp, "Front-end", "JS/React", "Behandelt veilige communicatie met verouderde externe APIs.")

Container_Boundary(apiComponents, "API Application Container") {
    Component(controller, "Gateway controller", "Spring REST Controller", "Behandelt verzoeken naar verouderde API's.")
    Component(service, "Gateway service", "Spring service", "Controleert of gebruiker toegang heeft.")
    Component(service2, "Verouderde API service", "Spring service", "Vervoert gegevens van de verouderde API.")
}

System_Ext(externalApi, "Verouderde Externe API", "Een verouderde API zonder beveiliging", "External System")
System_Ext(mockService, "Wiremock", "Geeft token terug als gebruiker juiste wachtwoord en naam goed heeft", "External System")

webapp --> controller : 1. Verzoek om in te loggen voor externe verouderde API
controller --> service : 2. Stuurt ingevoerde data naar de service
service --> mockService : 3. Stuurt ingevoerde data naar de mockService
mockService --> service : 4. Stuurt token terug naar de service
service --> externalApi : 5. Verzendt verzoeken om toegang voor de legacy API
externalApi --> service2 : 6. Stuurt gegevens terug naar de verouderde api service
service2 --> service : 7. Stuurt gegevens terug naar de service
service --> controller : 8. Stuurt gegevens terug naar de controller
controller --> webapp : 9. Stuurt gegevens terug naar de front-end

@enduml