@startuml

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

SHOW_PERSON_OUTLINE()

AddRelTag("sync/async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())

title Container diagram voor het triptop systeem

Person(reiziger, Reiziger, "Een persoon die een reis samen wilt stellen")

System_Ext(wiremock, "Identity Provider", "Geeft een token terug als je een geldige gebruikersnaam en wachtwoord geeft. WireMock")

System_Boundary("key_boundary", "Ans", $tags="") {
    Container(frontend, "Frontend", $techn="JS/React", $descr="Laat de pagina zien aan de gebruiker.", $tags="", $link="")
    Container(backend, "Backend", $techn="Java/Spring Boot", $descr="Laat locaties op die gekozen worden op de route door de gebruiker.", $tags="", $link="")
 }

reiziger --> frontend : 1. Voert gebruikersnaam en wachtwoord in
frontend --> backend : 2. Logt in met gebruikersnaam en wachtwoord
backend --> wiremock : 3. Geeft gegevens mee
wiremock --> backend : 4. Krijgt token of foutmelding terug
backend --> frontend : 5a. Stuurt token terug, of
backend --> frontend : 5b. Stuurt foutmelding terug

SHOW_LEGEND()

@enduml